### ISSUE TITLE
Cannot continue with the example

### ISSUE THREAD

**Issue by rohjunha** [alters-mit/magnebot#11]
I have been following the example here
```
from magnebot import Magnebot, Arm
m = Magnebot()
status = m.init_floorplan_scene(scene="2a", layout=1)
```

Now I got an error message below.
```
>>> status = m.init_floorplan_scene(scene="2a", layout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mai/jroh/miniconda3/envs/tdw/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 480, in init_floorplan_scene
    return self._init_scene(scene=scene_commands,
  File "/home/mai/jroh/miniconda3/envs/tdw/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 2364, in _init_scene
    status = self._do_arm_motion()
  File "/home/mai/jroh/miniconda3/envs/tdw/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 1853, in _do_arm_motion
    for i in range(len(state_0.joint_angles[a_id])):
KeyError: -1262053853

```

I have installed `tdw==1.8.21` and `magnebot==1.2.2`.

**Comment by alters-mit** [comment]
@rohjunha We've observed this bug in unrelated projects using the underlying TDW code. We're working on a bug fix. I'll let you know when it's released.
